name: Update Last Blog Content
on:
  schedule:
    # Runs action every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_readme:
    name: Update README with last blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://carnets-du-devops.fr/rss/"
