name: Update Last Blog Content
'on':
  schedule:
    # Runs action every hour
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Substack posts
        uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          feed_list: "https://resilientops.substack.com/feed"
